name = 'django_quicktrack'
version = '0.0.1'
description = 'Django app to quickly record when events happen.'
url = 'http://hg/Webapps/TestDataSystem'
author = 'Justin Engel'
author_email = 'jengel@sealandaire.com'
